firestone:
  hero_url: "https://static.zerotoheroes.com/api/bgs/hero-stats/mmr-{mmr}/{period}/overview-from-hourly.gz.json"
  trinket_url: "https://static.zerotoheroes.com/api/bgs/trinket-stats/{period}/overview-from-hourly.gz.json"
  brackets: ["100", "50", "25", "10", "1"]
  periods: ["last-patch"]
hsjson:
  cards_url_template: "https://api.hearthstonejson.com/v1/latest/{locale}/cards.json"
  art_url_template: "https://art.hearthstonejson.com/v1/render/latest/{locale}/512x/{cardId}.png"
  default_locale: "enUS"
  locales: ["enUS", "zhTW", "zhCN"]
